# Test against these versions of Node
environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  # Get the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
