version: 2

jobs:
  build_12:
    docker:
      - image: circleci/node:6
    working_directory: ~/node6
    steps:
      - checkout

      - restore_cache:
          keys:
            - 12-dep-{{ checksum "package.json" }}
            - 12-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 12-dep-{{ checksum "package.json" }}

      - run: yarn test

  build_14:
    docker:
      - image: circleci/node:8
    working_directory: ~/node8
    steps:
      - checkout

      - restore_cache:
          keys:
            - 14-dep-{{ checksum "package.json" }}
            - 14-dep-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: 14-dep-{{ checksum "package.json" }}

      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/deploy
    steps:
      - checkout

      - run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_12
      - build_14
      - approve: # Wait for AppVeyor's result
          type: approval
          requires:
            - build_12
            - build_14
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - approve
